# Generated by Django 3.1 on 2020-08-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='toDoList',
            new_name='toDo',
        ),
    ]
